fix(shadow): Fix shadow support in locator.js
codeceptjs/CodeceptJS pull request #2599
Opened 2020-09-24 20:51 UTC by patrjam

## Motivation/Description of the PR
- We need to use scrollTo method for scrolling on shadow elements - it didnt work correctly for this case.
- We also use resemble helper for visual testing, which uses webdriver methods and here was also problem with shadow selectors. This PR resolves both.
- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2585 

Applicable helpers:

- [ ] WebDriver

## Type of change

- [ ] :bug: Bug fix

## Checklist:

- [ok] Tests have been added
- [ok] Documentation has been added (Run `npm run docs`)
- [ok] Lint checking (Run `npm run lint`)
- [ok] Local tests are passed (Run `npm test`)

2020-09-26 08:04 UTC, DavertMik commented on test/unit/locator_test.js
> +        const l = new Locator('{ shadow: ["my-app", "recipe-hello-binding", "ui-input", "input.input"] }');
JavaScript object written as a string? 
A very strange design decision... :confused:

2020-10-05 06:32 UTC, patrjam commented
Still waiting for review. We need it ASAP.

@DavertMik

2020-10-05 10:46 UTC, DavertMik requested changes
I understand the issue but I don't agree on the way you fix it. 
Sure, we need shadow locators but we need to have a better policy on that.

Shadow locator must always be: object with array as parameters.

```js
{ shadow: ['a', 'b', 'c'] }
```

so isShadow should detect that value is object with `shadow` key.

2020-10-05 10:46 UTC, DavertMik commented on test/unit/locator_test.js
> +        const l = new Locator({ shadow: '["my-app", "recipe-hello-binding", "ui-input", "input.input"]' });
sorry, I still don't understand why do you pass it as string if you can pass it by array:

```js
{ shadow: ["my-app", "recipe-hello-binding", "ui-input", "input.input"] }
```

2020-10-05 10:46 UTC, DavertMik commented on lib/locator.js
> +  return locator[0] === '{';
no, this is a bad way to detect shadow locator

2020-10-06 15:49 UTC, patrjam commented
Updated.

2020-10-19 08:02 UTC, patrjam commented
Still waiting for review. @DavertMik 
Thanks.

2020-11-06 11:42 UTC, patrjam commented
Should review anyone else, please? Iam still waiting... e.g. @Vorobeyko, @PeterNgTr

2020-11-13 11:29 UTC, Trawais commented
Please guys. We can't wait for this one being fixed. @DavertMik @Vorobeyko @PeterNgTr @Georgegriff @elukoyanov Anybody else?

2020-11-13 11:50 UTC, Georgegriff commented
This pr is targeting the wrong branch please rebase to 3.x

2020-11-13 20:00 UTC, DavertMik commented
Thanks, all checks passed, should be fine to merge. Thank you. This fix will go to 3.0.3-beta

2020-11-13 20:00 UTC, merged