Fix context error
codeceptjs/CodeceptJS pull request #2692
Opened 2020-11-23 15:21 UTC by tsuemura

## Motivation/Description of the PR

When clicking a submit button in a post request form after opening a new tab, I encountered this error.

```
     Execution context was destroyed, most likely because of a navigation.
      at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:69:15)
      at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:54:53)
      at ElementHandle.getProperty (node_modules/playwright/lib/client/jsHandle.js:39:44)
      at Playwright.proceedSee (lib/helper/Playwright.js:2489:25)
```

![image](https://user-images.githubusercontent.com/17092259/99979843-eacf8d80-2dea-11eb-8a29-c425da75bd2b.png)

This PR will fix this issue.

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [x] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [x] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

2020-11-24 00:53 UTC, tsuemura commented
Aw, why all of the checks were failed? I think those are not related to my changes 🤔

2020-11-25 18:43 UTC, DavertMik approved these changes

2020-11-25 18:44 UTC, DavertMik requested changes
Tests are failing. Could you look into what's wrong?

2020-12-01 08:25 UTC, Arhell approved these changes

2020-12-18 18:43 UTC, DavertMik commented
Sorry, Playwright tests are failing because of this change
Can't accept it

2020-12-18 18:43 UTC, closed without merging