Issue 2937 fix
codeceptjs/CodeceptJS pull request #2938
Opened 2021-06-23 17:35 UTC by jancorvus

## Motivation/Description of the PR
- Description of this PR, which problem it solves

  Fixes broken paths in the typings file, if it located in sub-folders of a project, generated by the command
```bash
npx codeceptjs def -o folder/sub-folder
```
on Windows

- Resolves #2937

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

2021-06-25 00:17 UTC, Arhell approved these changes

2021-08-02 13:53 UTC, DavertMik commented
@jancorvus sorry for the delayed reply, but why does this PR touch Allure reporter?

2021-08-02 13:54 UTC, DavertMik requested changes
Allure changes not related to this PR

2021-08-02 14:13 UTC, DavertMik commented
Anyway, I'm merging because I merged another your PR

2021-08-02 14:13 UTC, merged