Check for helpers type rather than name
codeceptjs/CodeceptJS pull request #3010
Opened 2021-08-31 14:24 UTC by leonardonelson91

## Motivation/Description of the PR
This change slightly modifies the way the 'screenshotOnFail' plugin initializes its code. Currently, there is a verification for the supported helpers at the plugin initialization, comparing it by name. This does not allow for custom implementations of helpers like Appium, WebDriver etc on custom helpers that extend them, i.e.

class MyHelper extends Appium

The above will not activate the screenshotOnFail plugin as its not named as 'Appium', even though it inherits all of Appium's helper (including screenshot) functions

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

2021-08-31 23:34 UTC, DavertMik approved these changes
Thanks, I like the idea. Let me thing a bit more of it if this affects other plugins, because it may

2021-08-31 23:38 UTC, DavertMik requested changes
Thanks but seems to break other plugins.
Also, there might be 3rd party plugins that rely on the helper's name.

I agree that the change is needed.

But I think you should keep current behavior for BC just in case. And create a new file like 

`standardActingHelperClasses`

Then refactor plugins to use the new way of detecting a helper.

2021-09-01 00:13 UTC, Arhell approved these changes

2021-10-01 20:24 UTC, DavertMik commented
No updates for a month, unfortunately I have to close it.

2021-10-01 20:24 UTC, closed without merging