Handle matching/duplicate steps in cucumber style
codeceptjs/CodeceptJS pull request #3044
Opened 2021-09-15 15:06 UTC by abhimanyupandian

## Motivation/Description of the PR
Duplicate steps in step definition files are used in the order they are defined in the codecept configuration file. 
This change does a check for the closest step definition file containing the required step when the step is repeated in multiple files. This is similar to cucumbers logic.

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

2021-09-15 16:44 UTC, abhimanyupandian commented
@DavertMik Could you please review and merge this?

2021-09-16 00:10 UTC, Arhell approved these changes

2021-10-01 20:06 UTC, DavertMik requested changes
Sorry, this PR is too complex for me, and to be honest, I can't figure it out.
You can reach me in Slack next week to discuss this in detals. But for now I can't take it

2021-10-01 20:06 UTC, DavertMik commented on lib/interfaces/bdd.js
> +        const fn = (featureName && Object.keys(matchingSteps).includes(stepName)) ? _findClosestPath(featureName, matchingSteps[stepName]) : steps[stepName];
sorry, this code is so complicated that I can't understand it.
Please expand this construct so it would be possible to understand what happens here

2021-10-01 20:06 UTC, DavertMik commented on lib/interfaces/bdd.js
> +const _findClosestPath = (from, tos) => {
what is closest path here? From what to which? I can't get it

2021-10-01 20:06 UTC, DavertMik commented on lib/interfaces/bdd.js
> +      const fn = (featureName && Object.keys(matchingSteps).includes(stepName)) ? _findClosestPath(featureName, matchingSteps[stepName]) : steps[stepName];
again, I can't understand this. Please move this logic to a separate function if this is repeated 2 times.

2021-11-06 06:14 UTC, DavertMik commented
Sorry, this PR adds a too much conplexity by solving a minor issue. I would probably reject it. Again, i am open to discussion, maybe we can come up with cleaner solution. Thank you

2021-11-06 06:15 UTC, closed without merging