[Proposal] Add optional timeout on actor actions
codeceptjs/CodeceptJS pull request #3059
Opened 2021-10-02 13:46 UTC by nikocanvacom

## Motivation/Description of the PR
- In some situations CodeceptJS actor action hangs forever on very long or hanging helper methods. This PR adds timeout.
- Resolves #issueId (if applicable).

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

2021-10-03 00:20 UTC, Arhell approved these changes

2021-10-03 00:27 UTC, nikocanvacom commented
This PR happens to have some duplication with the work being done in https://github.com/codeceptjs/CodeceptJS/pull/2583 .
Also #2583 makes exception for `waitXXX` functions which is the right thing to do if you treat this change as feature rather than as a bugfix (which it is for my team).

Please read comments here and on the other PR and make your suggestions on what the minimal change is.

2021-10-06 07:56 UTC, DavertMik commented
Thanks, @nikocanvacom for the PR
This one looks leally good. #2583 seems to be abandoned so I left it opened just for inspiration. I think it worked.
I like your solution, however as it touches core I'm looking at it with caution. However, let's proceed with this. 

Please add documentation on how to use it. Then let's figure out how to add unit tests.

2021-10-06 08:10 UTC, DavertMik requested changes
I took a detailed look into this PR. At first, I like the idea, I think we really need it.

However, I don't like API here:

```js
I.timeout(30).click('Hello')
```
reads really bad... Maybe we can find a proper verb here? As `I.retry().click()` reads quite fine.

Just as an idea - maybe an implementation can be made similary to tryTo Plugin https://github.com/codeceptjs/CodeceptJS/blob/codeceptjs-v3.0/lib/plugin/tryTo.js ?
If so, it would be more clear to have it as a plugin.

I also added my comments to the code. And I would love to see this PR going and merged into CodeceptJS

2021-10-06 08:10 UTC, DavertMik commented on lib/container.js
> +    container.support = createSupportObjects(config.include || {}, config.globalActionTimeout);
I don't think we need to change how container works here. We need this param only for `actor` so let's not pass this var here

2021-10-06 08:10 UTC, DavertMik commented on lib/container.js
> +    objects.I.setTimeout(globalActionTimeout);
I think we can get this value from `config`...

2021-10-06 08:10 UTC, DavertMik commented on lib/recorder.js
> +  add(taskName, fn = undefined, force = false, retry = undefined, timeout = 0) {
let's make `timeout` undefined as default so we won't accidentlly run it on 0 second

2021-10-06 09:00 UTC, nikocanvacom commented on lib/actor.js
> +function recordStep(step, args, timeout) {
sure, I'll do this update

2021-10-31 19:22 UTC, DavertMik approved these changes
Thanks. Let's have it merged, I will write the documentation about this feature before the release

2021-10-31 19:24 UTC, merged