attach video to allure report if allure report is enabled
codeceptjs/CodeceptJS pull request #3198
Opened 2022-01-14 12:51 UTC by PeterNgTr

## Motivation/Description of the PR
- Currently we don't attach failed videos to allure report, so would be nice to see the failed videos are attached to allure report.

Applicable helpers:

- [x] Playwright

## Type of change

- [x] :rocket: New functionality

2022-01-14 23:40 UTC, Arhell approved these changes

2022-01-15 10:47 UTC, Arhell approved these changes

2022-01-18 18:29 UTC, jancorvus commented
@PeterNgTr , @Arhell ,
could we also cancel [this change](https://github.com/codeceptjs/CodeceptJS/blob/3.x/typings/index.d.ts#L200) because it is wrong and even this PR proves that.
I can't upgrade because of that line since I use type Mocha.test in my TSed helpers.

Thanks.

2022-01-25 09:48 UTC, DavertMik requested changes
This should be part of `allure.js` plugin, not Playwright
Playwright helper should know nothing about plugins currently enabled.

That's why we have `artifacts` option.

You can attach videos from alure plugin by going through all tests and getting video artifacts.
Also, please note, that videos are processed in the very end

2022-01-28 23:24 UTC, closed without merging